app_name = "zep_dummy_app"
app_title = "zep_dummy_app"
app_publisher = "Unknown"
app_description = "App generated by workflow"
app_email = "email@example.com"
app_license = "MIT"
# Make custom DocType available
fixtures = ["Projektanfrage"]
# Further configuration options are commented out for convenience.
# Apps
# ------------------

# required_apps = []

# Each item in the list will be shown as an app in the apps page
# add_to_apps_screen = [
#     {
#         "name": "zep_dummy_app",
#         "logo": "/assets/zep_dummy_app/logo.png",
#         "title": "zep_dummy_app",
#         "route": "/zep_dummy_app",
#         "has_permission": "zep_dummy_app.api.permission.has_app_permission"
#     }
# ]
